### PR TITLE
IDE-740 Remove native graph control

### PR DESCRIPTION
**Pull request by GordonSmith**
Remove the ActiveX graph control.

Signed-off-by: Gordon Smith <gordonjsmith@gmail.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@dehilsterlexis please review...

**Comment by dehilsterlexis** [comment]
@GordonSmith will look at it and do a thorough test on the IDE.

**Comment by richardkchapman** [comment]
@dehilsterlexis

**Comment by dehilsterlexis** [comment]
@richardkchapman still doing testing. Almost done.

**Comment by richardkchapman** [comment]
@dehilsterlexis I mention you to ensure that you are tracked as the owner. If you mention someone else every time you reply it defeats that process.

**Comment by dehilsterlexis** [comment]
@GordonSmith @richardkchapman looks good

**Pull request merged**
