### PR TITLE
Deft type

### PR DESCRIPTION
**Pull request by drealeed**
I had to open a new pull request with the additional changes added from the pull request view. Even though hpcc-systems/eclide was reattached as my upstream fork, the commits in this branch weren't reflected in the pr.

### CODE REVIEW

**Comment by GordonSmith** [comment]
@drealeed Looks good - can you squash those commits to a single commit?

**Comment by drealeed** [comment]
Never squashed stuff before; my attempts to do so wiped out the commits. I did a hardbase and remade the changes in a single commit.

**Comment by GordonSmith** [comment]
Looks good.

**Comment by richardkchapman** [comment]
See https://track.hpccsystems.com/browse/IDE-527

**Comment by richardkchapman** [comment]
Merged manually into 6.2 to fix up commit message

**Pull request closed without merging**
