### PR TITLE
IDE-803 Language colors don't seem to work 100%

### PR DESCRIPTION
**Pull request by dehilsterlexis**
Fixed IDE-803

Signed-off-by: dehilsterlexis <david.dehilster@lexisnexis.com>

### CODE REVIEW

**Comment by dehilsterlexis** [comment]
@GordonSmith this fixes one problem with the colorization. The only problem left is the single quote string colorization which appears to be a problem with scintilla, not our code. I will make a separate jira for that.

**Comment by richardkchapman** [comment]
Should this target 7.0.2?

**Comment by GordonSmith** [comment]
@dehilsterlexis can you re-target PR?

**Comment by GordonSmith** [comment]
@dehilsterlexis bump

**Comment by richardkchapman** [comment]
At this point 7.0.4 or maybe 7.0.6 would be the target

**Comment by GordonSmith** [comment]
@richardkchapman I re-targeted this change.

**Pull request merged**
