### PR TITLE
chore(build): Use vcpkg for third party libraries

### PR DESCRIPTION
**Pull request by GordonSmith**
Switch to gsoap v2.7.13 (v2.7.15 is not officially supported)

Minor string changes (wide to narrow) to remove compiler warnings

Signed-off-by: Gordon Smith <gordonjsmith@gmail.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@dehilsterlexis please review
 - Can you test with VS 2015 by creating a clean build folder and following the new instructions in the README.md file

**Comment by GordonSmith** [comment]
@dehilsterlexis (hold off on testing until I switch the third party libs to point at hpcc-systems variant)

**Comment by GordonSmith** [comment]
@dehilsterlexis did you checkout `GordonSmith/VCPKG` prior to the `submodule update --init --recursive` step?

**Comment by dehilsterlexis** [comment]
@GordonSmith the vcpkg **boost-asio** is failing. It says it "can't connect to the server" for the link http://download.qt.io/official_releases/jom/jom_1_1_2.zip. If you try this link in a browser, it seems to download. It is the only package that is failing. I'm not sure why not. I loaded all of them one at a time to find which was failing and only this one is.

**Comment by GordonSmith** [comment]
Can you retry in a clean folder?

**Comment by dehilsterlexis** [comment]
@GordonSmith I did that. I will try it again though.

**Comment by dehilsterlexis** [comment]
@GordonSmith got further! It is now failing on the compilation. Four failures that "appear" to be in the boost libraries. Everything via vcpkg worked.

$ cmake --build . --config RelWithDebInfo -- -m
Microsoft (R) Build Engine version 14.0.27522.0
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 12/6/2018 1:28:44 PM.

...<<<DELETED BY DE HILSTER>>

3>FinalizeBuildStatus:
         Deleting file "EN_US.dir\RelWithDebInfo\EN_US.tlog\unsuccessfulbuild".
         Touching "EN_US.dir\RelWithDebInfo\EN_US.tlog\EN_US.lastbuildstate".
     3>Done Building Project "C:\Users\DEHIDA01\git17\build\eclide\en_us\EN_US.vcxproj" (default targets).
     5>global.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) class boost::system::error_category const & __cdecl boost::system::detail::generic_category_ncx(void)" (__imp_?generic_category_ncx@detail@system@boost@@YAABVerror_category@23@XZ) referenced in function "public: __thiscall boost::lock_error::lock_error(int,char const *)" (??0lock_error@boost@@QAE@HPBD@Z) [C:\Users\DEHIDA01\git17\build\eclide\clib\CLIB.vcxproj]
     5>RecursiveMutex.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) class boost::system::error_category const & __cdecl boost::system::detail::generic_category_ncx(void)" (__imp_?generic_category_ncx@detail@system@boost@@YAABVerror_category@23@XZ) [C:\Users\DEHIDA01\git17\build\eclide\clib\CLIB.vcxproj]
     5>stdafx.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) class boost::system::error_category const & __cdecl boost::system::detail::generic_category_ncx(void)" (__imp_?generic_category_ncx@detail@system@boost@@YAABVerror_category@23@XZ) [C:\Users\DEHIDA01\git17\build\eclide\clib\CLIB.vcxproj]
     5>C:\Users\DEHIDA01\git17\build\eclide\bin\RelWithDebInfo\CLIB.dll : fatal error LNK1120: 1 unresolved externals [C:\Users\DEHIDA01\git17\build\eclide\clib\CLIB.vcxproj]
     5>Done Building Project "C:\Users\DEHIDA01\git17\build\eclide\clib\CLIB.vcxproj" (default targets) -- FAILED.
     7>FinalizeBuildStatus:
         Deleting file "ECLEDITOR.dir\RelWithDebInfo\ECLEDITOR.tlog\unsuccessfulbuild".
         Touching "ECLEDITOR.dir\RelWithDebInfo\ECLEDITOR.tlog\ECLEDITOR.lastbuildstate".
     7>Done Building Project "C:\Users\DEHIDA01\git17\build\eclide\EclEditor\ECLEDITOR.vcxproj" (default targets).
     6>FinalizeBuildStatus:
         Deleting file "BUGTRAP.dir\RelWithDebInfo\BUGTRAP.tlog\unsuccessfulbuild".
         Touching "BUGTRAP.dir\RelWithDebInfo\BUGTRAP.tlog\BUGTRAP.lastbuildstate".
     6>Done Building Project "C:\Users\DEHIDA01\git17\build\eclide\BugTrap\BUGTRAP.vcxproj" (default targets).
     9>FinalizeBuildStatus:
         Deleting file "SGRID.dir\RelWithDebInfo\SGRID.tlog\unsuccessfulbuild".
         Touching "SGRID.dir\RelWithDebInfo\SGRID.tlog\SGRID.lastbuildstate".
     9>Done Building Project "C:\Users\DEHIDA01\git17\build\eclide\sgrid\SGRID.vcxproj" (default targets).
     4>Done Building Project "C:\Users\DEHIDA01\git17\build\eclide\amt\AMT.vcxproj" (default targets) -- FAILED.
     1>Done Building Project "C:\Users\DEHIDA01\git17\build\eclide\ALL_BUILD.vcxproj" (default targets) -- FAILED.

Build FAILED.**

**Comment by dehilsterlexis** [comment]
@GordonSmith we need to add to the readme file that the ECLReference.chm file needs to be copied into the docs directory for creating the install.

**Comment by GordonSmith** [comment]
@dehilsterlexis I made the chm file optional (at generation time).

Also I cleaned up how the comms/gsoap generated files are created and included (they were getting recompiled on every build that had a cpp change in comms).

**Comment by GordonSmith** [comment]
@richardkchapman should be ready for pull (I will re-target 7.2.0).  
@cloLN this will affect the Jenkins build server.

**Comment by cloLN** [comment]
mention @xwang2713 as well since he should know.

**Comment by GordonSmith** [comment]
@richardkchapman this can be pulled

**Comment by richardkchapman** [comment]
@xwang2713 Can you test this with Jenkins please

**Comment by xwang2713** [comment]
Sure.

**Comment by xwang2713** [comment]
Initial build failed due to CMakeLists.txt assume vcpkg/buildtrees are under ECLIDE directory. Also vcpkg can't find scintilla, gsoap, BugTrap and zlib. 
Already ask @dehilsterlexis for help.  Maybe just copy all buildtree for each build?

**Comment by GordonSmith** [comment]
@xwang2713 - let me take another run at this, I know the gsoap sources got patched and moved, also it would be better if we forked all the sources (where possible).

**Comment by GordonSmith** [comment]
@xwang2713 can you retest?

**Comment by GordonSmith** [comment]
@xwang2713 bump

**Comment by GordonSmith** [comment]
Closing in favor of:  https://github.com/hpcc-systems/eclide/pull/458

**Pull request closed without merging**
