### PR TITLE
IDE-622 Submit Selected short cut not working

### PR DESCRIPTION
**Pull request by dehilsterlexis**
Wrong text on the menu hint

### CODE REVIEW

**Comment by dehilsterlexis** [comment]
I need to rebase this.

**Comment by dehilsterlexis** [comment]
@GordonSmith for review

**Comment by richardkchapman** [comment]
Typo in commit message

**Comment by richardkchapman** [comment]
Any reason this does not target 6.4.0?

**Comment by GordonSmith** [comment]
Yup should be targeting 6.4

**Comment by richardkchapman** [comment]
@dehilsterlexis

**Comment by dehilsterlexis** [comment]
@richardkchapman should go in 6.4. James put in the change foor the documentation as well. Need to make sure that change goes together.

**Comment by richardkchapman** [comment]
@dehilsterlexis Please rebase the commit onto 6.4.0 and then edit this pull request...

**Comment by dehilsterlexis** [comment]
@richardkchapman back to you

**Pull request merged**
