### PR TITLE
IDE-665 Show DESDL Details page on publish

### PR DESCRIPTION
**Pull request by richardkchapman**
Fixes IDE-665

Signed-off-by: Gordon Smith <gordonjsmith@gmail.com>

### CODE REVIEW

**Comment by richardkchapman** [comment]
Replaces #378

**Comment by richardkchapman** [comment]
@rpastrana @dehilsterlexis Please review

**Comment by richardkchapman** [comment]
This is gordon's commit, rebased onto latest 6.4.0 after David's change was merged

**Comment by dehilsterlexis** [comment]
@richardkchapman @rpastrana There is a problem with the landing page for ESDL publish. I have alerted Gordon by email. It is not easily solved. I will look to see if we can land on the general page for now.

**Comment by richardkchapman** [comment]
This change may need to wait for a later RC / point release then

**Comment by rpastrana** [comment]
@richardkchapman David's change alters a url gordon used in his change (Gordon didn't have the specific url and left it as a placeholder). Can David cherry-pick this, make his change and pull request that branch? All before monday EOD?

**Comment by dehilsterlexis** [comment]
@richardkchapman @rpastrana in my opinion yes. Wait for the point release. I also have run into the problem that the webpage coming in the IDE is not functional. Solving this quickly is unlikely. Users can still see the ESDL Publish on the webpage live in a browser.

**Comment by rpastrana** [comment]
@dehilsterlexis this should target 6.4.2

**Comment by GordonSmith** [comment]
@richardkchapman can you close in favour of:  https://github.com/hpcc-systems/eclide/pull/383

**Pull request closed without merging**
