### PR TITLE
IDE-870 Compilation failing because of CreateFile function name clash in EclMeta.cpp

### PR DESCRIPTION
**Pull request by dehilsterlexis**

### CODE REVIEW

**Comment by dehilsterlexis** [comment]
@xwang2713 here is the fix for the compiling problem.

**Comment by dehilsterlexis** [comment]
@xwang2713 please review.

**Comment by xwang2713** [comment]
Looks good.  Test build run successfully.

**Comment by GordonSmith** [comment]
Change looks fine - but you need to rebase the PR.

**Comment by GordonSmith** [comment]
@dehilsterlexis can you rebase so we can pull?

**Comment by dehilsterlexis** [comment]
@xwang2713 @GordonSmith rebased

**Pull request merged**
