### PR TITLE
IDE-825 Move meta initialization into CreateIModule/Attribute

### PR DESCRIPTION
**Pull request by dehilsterlexis**
Signed-off-by: dehilsterlexis <david.dehilster@lexisnexis.com>

### CODE REVIEW

**Comment by dehilsterlexis** [comment]
@GordonSmith did this to move to my new branch for 2017. Will ping when I finish it.

**Comment by dehilsterlexis** [comment]
@GordonSmith for review

**Comment by dehilsterlexis** [comment]
@GordonSmith question: should I take out the meta button in this version? We talked about that going away. This current PR does not remove the checkbox.

**Comment by GordonSmith** [comment]
@dehilsterlexis You can issue a new PR for that.

**Comment by dehilsterlexis** [comment]
@GordonSmith for review

**Pull request merged**
