### PR TITLE
IDE-897 Install package is missing MFC DLLs

### PR DESCRIPTION
**Pull request by GordonSmith**
Enabled VS Folder View

Signed-off-by: Gordon Smith <gordonjsmith@gmail.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
Tested on clean Win 7 + IE 8

**Comment by GordonSmith** [comment]
@richardkchapman please review

**Comment by GordonSmith** [comment]
@xwang2713 / @dehilsterlexis please review

**Comment by dehilsterlexis** [comment]
@GordonSmith looks good

**Pull request merged**
