### PR TITLE
IDE-768 Double click attribute search locally should open builder window

### PR DESCRIPTION
**Pull request by dehilsterlexis**
Fixed IDE-768

Signed-off-by: dehilsterlexis <david.dehilster@lexisnexis.com>

### CODE REVIEW

**Comment by dehilsterlexis** [comment]
@GordonSmith for review

**Comment by richardkchapman** [comment]
@dehilsterlexis

**Comment by dehilsterlexis** [comment]
@GordonSmith back to you

**Comment by dehilsterlexis** [comment]
@richardkchapman

**Pull request merged**
