### PR TITLE
IDE-1114 build ECLIDE with corresponding Clienttools

### PR DESCRIPTION
**Pull request by xwang2713**
For 64bit compiler using 64bit otherwise using 32bit

We will further discuss 64bit clienttools issue when @GordonSmith is back

Signed off by xiaoming.wang@lexisnexisrisk.com

### CODE REVIEW

**Comment by xwang2713** [comment]
@dehilsterlexis please review

**Review by dehilsterlexis — APPROVED** [review]
Looks good

**Comment by xwang2713** [comment]
@ghalliday this is ready to merge

**Comment by GordonSmith** [comment]
The 32bit IDE install has included the 64bit client tools for quite a while now and am surprised that it is now causing an issue.  My understanding of how it works:
1. The IDE installer bundles the entire client tools installer as a "tmp" file
2. During the install the client tools installer is extracted and then "executed" with a "silent" cli switch

We know folks will hit issues with the 32bit client tools

**Pull request merged**
