### PR TITLE
IDE-1050 Upgrade GH Action to match HPCC-Platform pattern

### PR DESCRIPTION
**Pull request by GordonSmith**

### CODE REVIEW

**Comment by GordonSmith** [comment]
@ghalliday this is what the PR build will look like:  https://github.com/GordonSmith/eclide/actions/runs/7194420773

**Review by ghalliday — COMMENTED** [review]
@GordonSmith please can you provide more information about what this change is doing.  The jira doesn't contain much information about what it is achieving.  There is also a big chunk of code moved which is hard to isolate what changed within it.
The commit message should also be understandable in a change log without any context.

**Comment by GordonSmith** [comment]
> There is also a big chunk of code moved which is hard to isolate what changed within it.

FWIW the code wasn't changed as such, it was replaced with the HPCC-Platform code.

**Review by ghalliday — APPROVED** [review]
Thanks for the clarification - that made it much easier to understand.

**Pull request merged**
