### PR TITLE
IDE-645 Ensure IDE works with 64bit client tools

### PR DESCRIPTION
**Pull request by GordonSmith**
Fixes IDE-645

Signed-off-by: dehilsterlexis <david.dehilster@lexisnexis.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@dehilsterlexis can you test this with a 64bit ct install?  (and code review).

**Comment by dehilsterlexis** [comment]
@GordonSmith I checked out your branch and tested the new code. It in fact finds my 64 bit version. See:
image

**Comment by GordonSmith** [comment]
@dehilsterlexis If you happy it works can you code review?

**Comment by dehilsterlexis** [comment]
@GordonSmith @richardkchapman code looks good

**Pull request merged**
