### PR TITLE
IDE-680 IDE Crash when dropzone is misconfigured

### PR DESCRIPTION
**Pull request by GordonSmith**
Missing TpMachine info causes crash.

Signed-off-by: Gordon Smith <gordonjsmith@gmail.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@dehilsterlexis Please review

**Comment by dehilsterlexis** [comment]
@GordonSmith I had the fix as well and I was delayed in trying to find out how to print out an error to the error window. Do we report this or just let it go on processing?

**Comment by GordonSmith** [comment]
No error is needed as its not the TargetCluster.  I don't think that "machine" is actually used in the IDE.

**Comment by dehilsterlexis** [comment]
@richardkchapman looks good to merge.

**Pull request merged**
