### PR TITLE
IDE-711 Update Scintilla to 3.7.6

### PR DESCRIPTION
**Pull request by GordonSmith**
Signed-off-by: Gordon Smith <gordonjsmith@gmail.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@dehilsterlexis please review.

**Comment by dehilsterlexis** [comment]
Looks good. Compiles and runs fine.

**Comment by richardkchapman** [comment]
@GordonSmith All I see here are changes to support a change of scintilla version - should there be a change to a submodule or similar too?

**Comment by GordonSmith** [comment]
@richardkchapman The dependency instructions are updated on the wiki.

I can now include Scintilla as a submodule as there is a mirror of it in GitHub now if you prefer?  (this is a 7.0.0 change).

**Comment by richardkchapman** [comment]
@GordonSmith I will defer to you on that. Sounds sensible to me though.

**Comment by GordonSmith** [comment]
@richardkchapman / @dehilsterlexis Added Scintilla as a submodule.  @dehilsterlexis can you confirm this branch builds cleanly on your machine?  
Note:  You will need to do a `git submodule update --init` after you check it out.

**Comment by dehilsterlexis** [comment]
@GordonSmith I'm getting compile errors.

ide-711-compileerrors

**Comment by dehilsterlexis** [comment]
@GordonSmith @richardkchapman compiles and runs well. Good to go from me..

**Pull request merged**
