### PR TITLE
IDE-707 Opening empty Default workspace folder causes hang

### PR DESCRIPTION
**Pull request by dehilsterlexis**
Fixed IDE-707

Signed-off-by: dehilsterlexis <david.dehilster@lexisnexis.com>

### CODE REVIEW

**Comment by dehilsterlexis** [comment]
@GordonSmith when working on IDE-492, I came upon this freezing caused by an infinite loop while waiting for m_loaded != LOADING_FINISHED. This is the fix.

**Comment by GordonSmith** [comment]
It should be getting set here:  https://github.com/dehilsterlexis/eclide-1/blob/d5e6b88a16b5ad4165c1b02dc306a5d960096701/comms/WorkspaceItem.cpp#L68

But there could be an uncaught exception in ```threadLoadWorkunit``` which causes the infinite load.

**Comment by dehilsterlexis** [comment]
@GordonSmith I believe this is correct. This fix is for the edge condition where there are no work units in the default workspace folder. Thus, `threadLoadWorkunit` never gets called. The logic is that the `Load` function is entered only if the current state is `LOADING_UNKNOWN` which is set in the initialization of the workspace item. When opening an empty Default folder, there are no work units so the thread function `threadLoadWorkunit` never gets called. Since `m_loaded` get sets to `LOADING_STARTED` on the line before checking if there are any work units in the workspace, then it makes logical sense to set `m_loaded` to `LOADING_FINISHED` for this folder if no work units are found in that workspace.

**Comment by taidehilster** [comment]
@GordonSmith ping

**Pull request merged**
