### PR TITLE
IDE-735 Add option to disable GraphControl

### PR DESCRIPTION
**Pull request by GordonSmith**
Signed-off-by: Gordon Smith <gordonjsmith@gmail.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@dehilsterlexis please review.
@richardkchapman not ready for pull, need to decide if we default this off.

**Comment by GordonSmith** [comment]
@dehilsterlexis bump

**Comment by dehilsterlexis** [comment]
@GordonSmith looks good

**Comment by richardkchapman** [comment]
@GordonSmith What was the decision re default?

**Comment by GordonSmith** [comment]
@richardkchapman Going to default to on - so PR can be taken as is.

**Comment by richardkchapman** [comment]
"On" meaning disabled ?

**Comment by dehilsterlexis** [comment]
@richardkchapman yes

**Pull request merged**
