### PR TITLE
IDE 589

### PR DESCRIPTION
**Pull request by dehilsterlexis**
IDE-589 Syntax highlight HIPIE

Fixed IDE-589

Signed-off-by: dehilsterlexis <david.dehilster@lexisnexis.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@dehilsterlexis - does this need to be rebased?

**Comment by dehilsterlexis** [comment]
Yes, I was writing you a Flowdock message saying I need help with that.

**Comment by richardkchapman** [comment]
@dehilsterlexis Is this stalled?

**Comment by dehilsterlexis** [comment]
@GordonSmith @richardkchapman Closing in lieu of Gordon's IDE-589.

**Pull request closed without merging**
