### PR TITLE
IDE-821 Use VCPKG for third party libs

### PR DESCRIPTION
**Pull request by GordonSmith**
Minor string changes (wide to narrow) to remove compiler warnings
Check for sign file

Remove scintilla submodule

Signed-off-by: Gordon Smith <gordonjsmith@gmail.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@xwang2713  - can you retest - full instructions here: https://github.com/GordonSmith/eclide/blob/VCPKG_TRAVIS/README.md

Preferred VS version is 2017 (but 2015 should work as well).

**Comment by xwang2713** [comment]
wtl and gsoap download failed.  Should we consider make these two as submodules?

13:02:47 Building package wtl[core]:x86-windows... 
13:02:48 -- Downloading http://downloads.sourceforge.net/project/wtl/WTL%209.1/WTL%209.1.5321%20Final/WTL91_5321_Final.zip?r=&ts=1477467616&use_mirror=netix...
13:02:48 -- Downloading http://downloads.sourceforge.net/project/wtl/WTL%209.1/WTL%209.1.5321%20Final/WTL91_5321_Final.zip?r=&ts=1477467616&use_mirror=netix... Failed. Status: 22;"HTTP response code said error"
13:02:48 CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:172 (message):
13:02:48       
13:02:48       Failed to download file.
13:02:48       If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
13:02:48       variables to "https://user:password@your-proxy-ip-address:port/".
13:02:48       Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues
13:02:48 
13:02:48 Call Stack (most recent call first):
13:02:48   ports/wtl/portfile.cmake:3 (vcpkg_download_distfile)
13:02:48   scripts/ports.cmake:71 (include)
13:02:48 
13:02:48 
13:02:48 Error: Building package wtl:x86-windows failed with: BUILD_FAILED
13:02:48 Elapsed time for package wtl:x86-windows: 1.396 s
13:02:48 Starting package 88/88: gsoap:x86-windows
13:02:48 Building package gsoap[core]:x86-windows... 
13:02:50 -- Downloading https://sourceforge.net/projects/gsoap2/files/gsoap-2.7/gsoap_2.7.13.zip/download...
13:07:50 -- Downloading https://sourceforge.net/projects/gsoap2/files/gsoap-2.7/gsoap_2.7.13.zip/download... Failed. Status: 28;"Timeout was reached"
13:07:50 CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:172 (message):
13:07:50       
13:07:50       Failed to download file.
13:07:50       If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
13:07:50       variables to "https://user:password@your-proxy-ip-address:port/".
13:07:50       Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues
13:07:50 
13:07:50 Call Stack (most recent call first):
13:07:50   ports/gsoap/portfile.cmake:15 (vcpkg_download_distfile)
13:07:50   scripts/ports.cmake:71 (include)
13:07:50 
13:07:50 
13:07:50 Error: Building package gsoap:x86-windows failed with: BUILD_FAILED
13:07:50 Elapsed time for package gsoap:x86-windows: 5.027 min

...


13:07:50 SUMMARY
13:07:50     SUCCEEDED: 86
13:07:50     BUILD_FAILED: 2
13:07:50     POST_BUILD_CHECKS_FAILED: 0
13:07:50     FILE_CONFLICTS: 0
13:07:50     CASCADED_DUE_TO_MISSING_DEPENDENCIES: 0
13:07:50     EXCLUDED: 0

**Comment by GordonSmith** [comment]
@xwang2713 I have moved all the "sourceforge" dependency to our own cloned variants - can you retest (note - some of the readme steps may have changed)?

**Comment by dehilsterlexis** [comment]
@xwang2713 will do. It worked when I was in the office. At home it doesn't work.

**Comment by xwang2713** [comment]
Build successfully.

**Pull request merged**
