### PR TITLE
IDE-616 Single-letter NAMED outputs don't show letter

### PR DESCRIPTION
**Pull request by dehilsterlexis**
Fixed IDE-616

### CODE REVIEW

**Comment by dehilsterlexis** [comment]
@GordonSmith please review

**Comment by GordonSmith** [comment]
@dehilsterlexis Code looks fine some questions:
* Can you test with some one/two/three letter potential corner cases - specifically "ii" and "QQ" (narrow and wide):
* You added the padding to start of the string, it might be better (from an alignment point of view to add the padding to the end (assuming that works)?

**Comment by dehilsterlexis** [comment]
@GordonSmith padding the end worked. All tests look good. Back to you.

**Comment by GordonSmith** [comment]
@dehilsterlexis Can you retarget to candidate-6.4.0?

**Comment by richardkchapman** [comment]
@dehilsterlexis Can you confirm the answer to Gordon's question so I can merge

**Comment by dehilsterlexis** [comment]
@GordonSmith "i", "Q", "ii" and "QQ" have been tested and work.

**Pull request merged**
