### PR TITLE
IDE-683 Using IDE with local repository has some differences which are not desirable

### PR DESCRIPTION
**Pull request by dehilsterlexis**
Fixed IDE-683

Signed-off-by: dehilsterlexis <david.dehilster@lexisnexis.com>

### CODE REVIEW

**Comment by dehilsterlexis** [comment]
@GordonSmith for review. This is the last issue in this general jira which was not working. This will finally close IDE-683.

**Comment by richardkchapman** [comment]
Change may be good but the commit is wrong - looks like you did a --amend on the initial commit checkin or something?

**Comment by dehilsterlexis** [comment]
@richardkchapman @GordonSmith commit text corrected. Back to you.

**Comment by GordonSmith** [comment]
Title too long:  https://github.com/hpcc-systems/HPCC-Platform/wiki/Git-commit-message-guidelines

**Comment by dehilsterlexis** [comment]
@GordonSmith back to you

**Pull request merged**
