### PR TITLE
IDE-989 Submit Context menu intermittently disabled

### PR DESCRIPTION
**Pull request by dehilsterlexis**
Signed-off-by: David de Hilster <david.dehilster@lexisnexis.com>

### CODE REVIEW

**Comment by dehilsterlexis** [comment]
@GordonSmith for review

**Review by GordonSmith — APPROVED** [review]
Looks good.

**Comment by richardkchapman** [comment]
Please retarget to 7.12.x

**Comment by dehilsterlexis** [comment]
@richardkchapman rebased

**Comment by richardkchapman** [comment]
Cherry picked to 7.10.x for 7.10.32

**Pull request merged**
